INSERT INTO CITY (CityName, ProvinceID)
VALUES
('San Vicente del Raspeig','A'),
('Elche', 'A'),
('Torrevieja', 'A'),
('Orihuela', 'A'),
('Benidorm', 'A'),
('Alcoy', 'A'),
('Elda', 'A'),
('Denia', 'A'),
('Villajoyosa', 'A'),
('Santa Pola', 'A'),
('Villena', 'A'),
('Torrent', 'V'),
('Gandia', 'V'),
('Paterna', 'V'),
('Sagunto', 'V'),
('Alzira', 'V'),
('Mislata', 'V'),
('Burjassot', 'V'),
('Ontinyent', 'V'),
('Xàtiva', 'V'),
('Chirivella', 'V'),
('Hospitalet de Llobregat', 'B'),
('Badalona', 'B'),
('Terrassa', 'B'),
('Sabadell', 'B'),
('Mataró', 'B'),
('Santa Coloma de Gramenet', 'B'),
('Cornellà de Llobregat', 'B'),
('Sant Cugat del Vallès', 'B'),
('Manresa', 'B'),
('Granollers', 'B'),
('Móstoles', 'M'),
('Alcalá de Henares', 'M'),
('Fuenlabrada', 'M'),
('Leganés', 'M'),
('Getafe', 'M'),
('Dos Hermanas', 'SE'),
('Alcalá de Guadaíra', 'SE'),
('Utrera', 'SE'),
('Mairena del Aljarafe', 'SE'),
('Écija', 'SE'),
('Gijón', 'O'),
('Vigo', 'PO'),
('Marbella', 'MA'),
('Cartagena', 'MU'),
('Jerez de la Frontera', 'CA'),
('Barakaldo', 'BI'),
('Talavera de la Reina', 'TO'),
('Ponferrada', 'LE'),
('Algeciras', 'CA');
