USE ROOMIE
GO

INSERT INTO FURNITURE (FurnitureName)
VALUES ('Bedroom desk')
	, ('Bed')
	, ('Armchair')
	, ('Nightstand')
	, ('Desktop')
	, ('Simple shelf')
	, ('Display shelf')
	, ('Standing lamp')
	, ('Office chair')
	, ('Rolling cart')
	, ('Coffee table')
	, ('Dining room table')
	, ('Sofa')
	, ('Television')
	, ('Wardrobe')
	, ('Dining room chair')
	, ('Rug')
	, ('Ceiling lamp')
	, ('Display case')
	, ('Cupboard')
	, ('Pillow')
	, ('Ceiling fan')
	, ('Cabinet')
GO