USE ROOMIE
GO

INSERT INTO PROVINCE (ProvinceName, ProvinceID)
VALUES ('Ávala', 'VI')
	, ('Albacete', 'AB')
	, ('Alicante', 'A')
	, ('Almería', 'AL')
	, ('Asturias', 'O')
	, ('Ávila', 'AV')
	, ('Badajoz', 'BA')
	, ('Barcelona', 'B')
	, ('Burgos', 'BU')
	, ('Cádiz', 'CA')
	, ('Cantabria', 'S')
	, ('Cáceres', 'CC')
	, ('Castellón', 'CS')
	, ('Ceuta', 'CE')
	, ('Ciudad Real', 'CR')
	, ('Córdoba', 'CO')
	, ('La Coruña', 'C')
	, ('Cuenca', 'CU')
	, ('Las Palmas de Gran Canaria', 'GC')
	, ('Girona', 'GI')
	, ('Granada', 'GR')
	, ('Guadalajara', 'GU')
	, ('Guipúzcua', 'SS')
	, ('Huelva', 'H')
	, ('Islas Baleares', 'IB')
	, ('Jaén', 'J')
	, ('León', 'LE')
	, ('Lérida', 'L')
	, ('La Rioja', 'LO')
	, ('Lugo', 'LU')
	, ('Madrid', 'M')
	, ('Málaga', 'MA')
	, ('Melilla', 'ML')
	, ('Murcia', 'MU')
	, ('Navarra', 'NA')
	, ('Ourense', 'OU')
	, ('Palencia', 'P')
	, ('Pontevedra', 'PO')
	, ('Salamanca', 'SA')
	, ('Segovia', 'SG')
	, ('Sevilla', 'SE')
	, ('Soria', 'SO')
	, ('Tarragona', 'T')
	, ('Santa Cruz de Tenerife', 'TF')
	, ('Teruel', 'TE')
	, ('Toledo', 'TO')
	, ('Valencia', 'V')
	, ('Valladolid', 'VA')
	, ('Vizcaya', 'BI')
	, ('Zamora', 'ZA')
	, ('Zaragoza', 'Z')
GO