USE ROOMIE
GO

CREATE TABLE PROVINCE(
ProvinceID CHAR(2) PRIMARY KEY
, ProvinceName CHAR(22) UNIQUE NOT NULL
)
GO

CREATE TABLE CITY(
CityID SMALLINT IDENTITY PRIMARY KEY
, CityName VARCHAR(50) NOT NULL
, ProvinceID CHAR(2) NOT NULL
, FOREIGN KEY (ProvinceID) REFERENCES PROVINCE(ProvinceID)
)
GO

CREATE TABLE INSTITUTION(
InstitutionID SMALLINT IDENTITY PRIMARY KEY
, InstitutionName VARCHAR(50) NOT NULL
, CityID SMALLINT NOT NULL
, FOREIGN KEY (CityID) REFERENCES CITY(CityID)
)
GO

CREATE TABLE PROPERTY_INSITUTION(
InstitutionID SMALLINT NOT NULL
, PropertyAddress VARCHAR(150) NOT NULL
, PRIMARY KEY (InstitutionID, PropertyAddress)
, FOREIGN KEY (InstitutionID) REFERENCES INSTITUTION(InstitutionID)
, FOREIGN KEY (PropertyAddress) REFERENCES PROPERTY(Address)
)
GO