@startuml
 skinparam classAttributeIconSize 0

package "Roomie"
{
    package "usuarios"
    {
        Class Usuario
        {
            - nombre: String
            - apellidos: String
            - dni: String
        }

        Class Arrendador extends Usuario
        {
            - listaPisos: ArrayList<Piso>

            + anyadirPiso(Piso piso): void
            + borrarPiso(Piso piso): void
        }

        Class Inquilino extends Usuario
        {
            - habitacion: Habitacion

            + alquilarHabitacion(habitacion: Habitacion): void
            + salirHabitacion(habitacion: Habitacion): void
        }
    }

    package "inmuebles"
    {
        Class Habitacion
        {
            - tamanyo: double
            - tipo: String
            - listaMuebles: ArrayList<Mueble>
            - numeroHabitacion: int

            + crearMueble(): void
            + borrarMueble(): void
        }

        Class Mueble
        {
            - nombre: String
            - tipo: String
            - numeroMueble: int
        }

        Class Piso
        {
            - direccion: String
            - tamanyo: double
            - listaHabitaciones: ArrayList<Habitacion>

            + crearHabitacion(): void
            + borrarHabitacion(): void
            + mostrarZonasComunes(): void
            + mostrarElectrodomesticos(): void
            + mostrarDormitorios(): void
        }
    }

    Inquilino o--> Habitacion
    Habitacion *--> Mueble
    Arrendador o--> Piso
    Piso *--> Habitacion
}
@enduml